CREATE TABLE AIRPORTS(
 id INT PRIMARY KEY,
 ident VARCHAR (50) UNIQUE NOT NULL,
 type VARCHAR (50) NOT NULL,
 name VARCHAR(2000),
 latitude_deg NUMERIC,
 longitude_deg NUMERIC,
 elevation_ft NUMERIC,
 continent VARCHAR (50),
 iso_country VARCHAR (50),
 iso_region VARCHAR (50),
 municipality VARCHAR (200),
 scheduled_service VARCHAR (50),
 gps_code VARCHAR (50),
 iata_code VARCHAR (50),
 local_code VARCHAR (50),
 home_link VARCHAR (2000),
 wikipedia_link VARCHAR (2000),
 keywords VARCHAR (2000)
);
